# Settings block.
drive=Z:
username=guest
password=
persist=true
replace_gateway=true

# Separate link entries with a blank line.
source=\\gateway\POE\Content.ggpk
link=C:\Games\Path of Exile\Content.ggpk
kind=file
